name: CJD_Epi 
channels:
  - conda-forge
dependencies:
# Add explicit version numbers to freeze a dependency.
# e.g. - python=3.10.6
  - python 
  - pyyaml 
  - numpy
  - matplotlib
  - gitpython
  - termcolor
  - colorama
  - jupyter
  - linearmodels
  # - julia 
  # - pip
  # - pip: # if there is a package available via pip but not with conda, can import like this:
  - r = 4.2.1
  - r-yaml # import r packages by prepending with "r-"
  - r-readr = 2.1.2
  - r-tidyverse = 1.3.1
  - r-lubridate = 1.8.0
  - r-data.table = 1.14.2
  - r-skimr = 2.1.4
  - r-Hmisc = 4.7.0
  - r-summarytools = 1.0.1
  - r-ggrepel = 0.9.2
  - r-ggforce = 0.4.1
  - r-gghighlight = 0.4.0
  - r-patchwork = 1.1.1
  - r-gridExtra = 2.3